### ISSUE TITLE
Fix minor bug in SPI

### ISSUE THREAD

**Issue by DavidFiumano** [DavidFiumano/MSP430-FreeRTOS-Drivers#13]
In the SPI transfer function, change lines 251 and 252 to wait for the maximum delay before continuing. It is true that the mutexes are guaranteed to be taken eventually, but for slower SPI speeds (i.e., 1/16th of the MCLK speed) we may need to wait for them to finish before taking the mutex.

**Comment by DavidFiumano** [comment]
Accidentally clicked closed.

**Comment by DavidFiumano** [comment]
Also add code to ensure that TxBuffer and RxBuffer are the same size. Return an error if they are not.

**Comment by DavidVFiumano** [comment]
This has been fixed in the addExamples branch and merged into master.
