### ISSUE TITLE
Fix/Improve UART class

### ISSUE THREAD

**Issue by GMUSatCom** [DavidFiumano/MSP430-FreeRTOS-Drivers#7]
The UART class has a tendency to miss characters when the connection gets close to saturated (for example, when using a GPS). Do the following to fix this:
- [x] Use static ring buffers instead of FreeRTOS queues to get data from the ISR. This should be faster than using the queues and free up more CPU cycles for processing
- [x] Use direct to task notifications to make waitOnRx() work since these are ~45% faster than queue operations
- [x] Move Clock parameters from the constructor to begin().
- [x] Add an end() function that turns off the UART port

**Comment by DavidFiumano** [comment]
Currently, there is a bug causing low power modes in the idle loop to make the eUSCI_A module miss the first character. Before this wasn't an issue but I have no idea why it is now. Working on a fix now.

**Comment by DavidFiumano** [comment]
end() now works. However, sending characters quickly makes messages get cutoff (a consequence of the underlying datastructure not being an RTOS queue anymore). I have to find a way to fix this.
